name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: action/checkout@v3
      - name: Setup Java
        uses: action/setup-java@v3
        with:
          distribution: 'openjdk'
          java-varsion: '17'
      - name: Build Project
        run: ./gradlew clean build -x test
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER.PASSWORD}}
      - name: Build docker image
        run: docker build -t enzofly/springboot-rest-demo-hub .
      - name: Publish image to docker hub
        run: docker push enzofly/springboot-rest-demo-hub:latest

